backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - name: "homepage"
        label: "Homepage Content"
        file: "content/site.json"
        fields:
          - {label: "Brand Name", name: "brand", widget: "string", default: "Vivid Finish Remodeling"}
          - {label: "Phone", name: "phone", widget: "string", default: "(210) 722-9189"}
          - {label: "Email", name: "email", widget: "string", default: "realvividrei@gmail.com"}
          - {label: "City", name: "city", widget: "string", default: "San Antonio, TX"}
          - {label: "Hero Headline", name: "heroTitle", widget: "string", default: "Remodels that feel like home."}
          - {label: "Hero Subtext", name: "heroSub", widget: "text", default: "Modern + Southwestern • Venetian Plaster Specialists"}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Alt text", name: "alt", widget: "string"}
